# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "/home/pong/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "/home/pong/Xilinx/workspace/project_1/project_1.srcs/sources_1/ip/cg_lin_index_map.xml"

set cgProjectPath "/home/pong/fpga_clase5a/FPGALink/rtl/loopFPGALink/cores/fifo8to32/coregen.cgc"

set ipFile "/home/pong/fpga_clase5a/FPGALink/rtl/loopFPGALink/cores/fifo8to32/fifo8to32.xco"

set ipName "fifo8to32"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "/home/pong/fpga_clase5a/FPGALink/rtl/loopFPGALink/cores/fifo8to32/pa_cg_bom.xml"

set cgPartSpec "xc3s500e-5fg320"

set hdlType "VHDL"

# generate the IP
set result [source "/home/pong/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

